set(OAK_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

set(OAK_SRC_DIR ${OAK_SOURCE_DIR}/src)
set(OAK_INCLUDE_DIR ${OAK_SOURCE_DIR}/include)
set(OAK_TESTS_DIR ${OAK_SOURCE_DIR}/tests)
set(OAK_EXAMPLES_DIR ${OAK_SOURCE_DIR}/examples)
set(OAK_WASM_DIR ${OAK_SOURCE_DIR}/wasm)

file(GLOB_RECURSE OAK_CORE_SOURCES CONFIGURE_DEPENDS ${OAK_SRC_DIR}/*.c)
file(GLOB_RECURSE OAK_TEST_SOURCES CONFIGURE_DEPENDS ${OAK_TESTS_DIR}/*/*.c)

set(OAK_SRC_INCLUDE_DIRS
    ${OAK_SRC_DIR}
    ${OAK_SRC_DIR}/common
    ${OAK_SRC_DIR}/runtime
    ${OAK_SRC_DIR}/lexer
    ${OAK_SRC_DIR}/parser
    ${OAK_SRC_DIR}/compiler
    ${OAK_SRC_DIR}/vm
)

set(OAK_APP_SOURCES
    ${OAK_SOURCE_DIR}/oak.c
    ${OAK_SOURCE_DIR}/oak_cli.c
)
