#include "oak_test_token.h"

OAK_TEST_DECL(LexOperators)
{
  struct oak_lexer_result_t* lexer =
      OAK_LEX("== != -> && || >= <= += -= *= /= %= : , ; = ! - + * / % ( ) "
              "{ } [ ] > < . ?");

  static struct oak_expected_token_t expected_tokens[] = {
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_EQUAL_EQUAL, 1),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_BANG_EQUAL, 4),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_ARROW, 7),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_AND, 10),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_OR, 13),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_GREATER_EQUAL, 16),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_LESS_EQUAL, 19),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_PLUS_ASSIGN, 22),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_MINUS_ASSIGN, 25),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_STAR_ASSIGN, 28),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_SLASH_ASSIGN, 31),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_PERCENT_ASSIGN, 34),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_COLON, 37),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_COMMA, 39),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_SEMICOLON, 41),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_ASSIGN, 43),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_BANG, 45),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_MINUS, 47),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_PLUS, 49),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_STAR, 51),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_SLASH, 53),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_PERCENT, 55),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_LPAREN, 57),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_RPAREN, 59),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_LBRACE, 61),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_RBRACE, 63),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_LBRACKET, 65),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_RBRACKET, 67),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_GREATER, 69),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_LESS, 71),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_DOT, 73),
    OAK_EXPECT_TOKEN_AT(OAK_TOKEN_QUESTION, 75),
  };

  const usize n = oak_count_of(expected_tokens);
  const enum oak_test_status_t result =
      oak_test_tokens(lexer, expected_tokens, n);
  oak_lexer_free(lexer);
  return result;
}

OAK_TEST_MAIN(LexOperators)
