#include "oak_tok.h"

const char* oak_tok_name(const oak_tok_type_t token_type)
{
  switch (token_type)
  {
  case OAK_TOK_IDENT:
    return "IDENT";
  case OAK_TOK_LPAREN:
    return "LPAREN";
  case OAK_TOK_RPAREN:
    return "RPAREN";
  case OAK_TOK_LBRACE:
    return "LBRACE";
  case OAK_TOK_RBRACE:
    return "RBRACE";
  case OAK_TOK_LBRACKET:
    return "LBRACKET";
  case OAK_TOK_RBRACKET:
    return "RBRACKET";
  case OAK_TOK_COMMA:
    return "COMMA";
  case OAK_TOK_SEMICOLON:
    return "SEMICOLON";
  case OAK_TOK_COLON:
    return "COLON";
  case OAK_TOK_EQUAL:
    return "EQUAL";
  case OAK_TOK_NOT_EQUAL:
    return "NOT_EQUAL";
  case OAK_TOK_EXCLAMATION_MARK:
    return "EXCLAMATION_MARK";
  case OAK_TOK_QUESTION_MARK:
    return "QUESTION_MARK";
  case OAK_TOK_LESS:
    return "LESS";
  case OAK_TOK_LESS_EQUAL:
    return "LESS_EQUAL";
  case OAK_TOK_GREATER:
    return "GREATER";
  case OAK_TOK_GREATER_EQUAL:
    return "GREATER_EQUAL";
  case OAK_TOK_SLASH:
    return "SLASH";
  case OAK_TOK_PERCENT:
    return "PERCENT";
  case OAK_TOK_ARROW:
    return "ARROW";
  case OAK_TOK_DOT:
    return "DOT";
  case OAK_TOK_PLUS:
    return "PLUS";
  case OAK_TOK_MINUS:
    return "MINUS";
  case OAK_TOK_STAR:
    return "STAR";
  case OAK_TOK_LET:
    return "LET";
  case OAK_TOK_MUT:
    return "MUT";
  case OAK_TOK_IF:
    return "IF";
  case OAK_TOK_ELSE:
    return "ELSE";
  case OAK_TOK_WHILE:
    return "WHILE";
  case OAK_TOK_FOR:
    return "FOR";
  case OAK_TOK_BREAK:
    return "BREAK";
  case OAK_TOK_CONTINUE:
    return "CONTINUE";
  case OAK_TOK_RETURN:
    return "RETURN";
  case OAK_TOK_TRUE:
    return "TRUE";
  case OAK_TOK_FALSE:
    return "FALSE";
  case OAK_TOK_AND:
    return "AND";
  case OAK_TOK_OR:
    return "OR";
  case OAK_TOK_NOT:
    return "NOT";
  case OAK_TOK_INT_NUM:
    return "INT_NUM";
  case OAK_TOK_FLOAT_NUM:
    return "FLOAT_NUM";
  case OAK_TOK_STRING:
    return "STRING";
  case OAK_TOK_ASSIGN:
    return "ASSIGN";
  case OAK_TOK_EOF:
    return "EOF";
  default:
    return "INVALID";
  }
}